/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import sistema.Administrador;
import sistema.Pessoa;
import sistema.Sistema;

/**
 *
 * @author Aluno
 */
public class TelaCadastro extends javax.swing.JFrame {
    GerenciandorTelas gerenciadorTelas;
    Sistema sys;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        gerenciadorTelas = GerenciandorTelas.getInstanceOfGerenciadorTealas();
        sys = GerenciandorTelas.getInstanceOfSistema();
        Pessoa p = sys.getUsuarioLogado();
        this.tipoUsuarioList.removeAll();
        this.tipoUsuarioList.addItem("Profissional");
        this.tipoUsuarioList.addItem("Cliente");
        
        
        if ( p != null ){
            if ( p instanceof Administrador){
                this.tipoUsuarioList.addItem("Administrador");
            }
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTxtField = new javax.swing.JTextField();
        enderecoTxtField = new javax.swing.JTextField();
        emailTxtField = new javax.swing.JTextField();
        telefoneTxtField = new javax.swing.JTextField();
        nomeUsuarioTxtField = new javax.swing.JTextField();
        senhaField = new javax.swing.JPasswordField();
        senhaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cadastrarButton = new javax.swing.JButton();
        tipoUsuarioList = new javax.swing.JComboBox<>();
        sairButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nomeTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeTxtFieldFocusLost(evt);
            }
        });
        nomeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxtFieldActionPerformed(evt);
            }
        });

        enderecoTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enderecoTxtFieldFocusGained(evt);
            }
        });

        emailTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTxtFieldFocusGained(evt);
            }
        });

        telefoneTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefoneTxtFieldFocusGained(evt);
            }
        });

        nomeUsuarioTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeUsuarioTxtFieldFocusGained(evt);
            }
        });

        senhaField.setText("jPasswordField1");
        senhaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaFieldFocusGained(evt);
            }
        });
        senhaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaFieldKeyPressed(evt);
            }
        });

        senhaLabel.setText("Senha :");

        jLabel1.setText("Nome :");

        jLabel2.setText("E-mail:");

        jLabel3.setText("Telefone :");

        jLabel4.setText("Endereco :");

        jLabel5.setText("Nome de usuario :");

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        tipoUsuarioList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoUsuarioListActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Selecione o tipo do usuário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(emailTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                        .addComponent(nomeTxtField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel1))
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipoUsuarioList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(senhaLabel)
                    .addComponent(telefoneTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(enderecoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(senhaField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addComponent(nomeUsuarioTxtField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(enderecoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUsuarioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(senhaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton)
                    .addComponent(sairButton))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoUsuarioList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtFieldActionPerformed

    private void nomeTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTxtFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtFieldFocusGained

    private void emailTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtFieldFocusGained

    private void telefoneTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneTxtFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneTxtFieldFocusGained

    private void enderecoTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enderecoTxtFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoTxtFieldFocusGained

    private void nomeUsuarioTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeUsuarioTxtFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUsuarioTxtFieldFocusGained

    private void senhaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFieldFocusGained
        // TODO add your handling code here:
        senhaField.setText("");
    }//GEN-LAST:event_senhaFieldFocusGained

    private void nomeTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTxtFieldFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nomeTxtFieldFocusLost

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void senhaFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaFieldKeyPressed
        // TODO add your handling code here:
       if( evt.getKeyCode() == Teclas.ENTER){
           this.cadastrarButton.doClick();
       }
    }//GEN-LAST:event_senhaFieldKeyPressed

    private void tipoUsuarioListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoUsuarioListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoUsuarioListActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        switch ((String) tipoUsuarioList.getSelectedItem()) {
            case "Profissional":
                sys.cadastraProfissional(nomeTxtField.getText(),
                    enderecoTxtField.getText(), emailTxtField.getText(), 
                    telefoneTxtField.getText(), nomeUsuarioTxtField.getText(),
                    String.valueOf(senhaField.getPassword()));
               break;
            case "Cliente":
                sys.cadastraCliente(nomeTxtField.getText(),
                    enderecoTxtField.getText(), emailTxtField.getText(), 
                    telefoneTxtField.getText(), nomeUsuarioTxtField.getText(),
                    String.valueOf(senhaField.getPassword()));
               break;
            case "Administrador":
                sys.cadastraAdmin(nomeTxtField.getText(),
                    enderecoTxtField.getText(), emailTxtField.getText(), 
                    telefoneTxtField.getText(), nomeUsuarioTxtField.getText(),
                    String.valueOf(senhaField.getPassword()));
               break;
                
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JTextField enderecoTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeTxtField;
    private javax.swing.JTextField nomeUsuarioTxtField;
    private javax.swing.JButton sairButton;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JTextField telefoneTxtField;
    private javax.swing.JComboBox<String> tipoUsuarioList;
    // End of variables declaration//GEN-END:variables
}
